# Generated by Django 5.0.4 on 2024-04-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
